/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 15 "example1.c"
void __globinit_example1(void) ;
extern void __CrestInit(void)  __attribute__((__crest_skip__)) ;
extern void __CrestHandleReturn(int id , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestReturn(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestCall(int id , unsigned int fid )  __attribute__((__crest_skip__)) ;
extern void __CrestBranch(int id , int bid , unsigned char b )  __attribute__((__crest_skip__)) ;
extern void __CrestApply2(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestApply1(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestClearStack(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestStore(int id , unsigned long addr )  __attribute__((__crest_skip__)) ;
extern void __CrestLoad(int id , unsigned long addr , long long val )  __attribute__((__crest_skip__)) ;
#line 216 "/usr/lib/gcc/arm-linux-gnueabihf/6/include/stddef.h"
typedef unsigned int size_t;
#line 65 "/usr/include/arm-linux-gnueabihf/bits/types.h"
typedef long long __quad_t;
#line 150 "/usr/include/arm-linux-gnueabihf/bits/types.h"
typedef long __off_t;
#line 151 "/usr/include/arm-linux-gnueabihf/bits/types.h"
typedef __quad_t __off64_t;
#line 4 "/usr/include/arm-linux-gnueabihf/bits/types/__FILE.h"
struct _IO_FILE;
#line 4
struct _IO_FILE;
#line 4 "/usr/include/arm-linux-gnueabihf/bits/types/FILE.h"
struct _IO_FILE;
#line 7 "/usr/include/arm-linux-gnueabihf/bits/types/FILE.h"
typedef struct _IO_FILE FILE;
#line 35 "/usr/include/arm-linux-gnueabihf/bits/types/struct_FILE.h"
struct _IO_FILE;
#line 36
struct _IO_marker;
#line 36
struct _IO_marker;
#line 37
struct _IO_codecvt;
#line 37
struct _IO_codecvt;
#line 38
struct _IO_wide_data;
#line 38
struct _IO_wide_data;
#line 43 "/usr/include/arm-linux-gnueabihf/bits/types/struct_FILE.h"
typedef void _IO_lock_t;
#line 49 "/usr/include/arm-linux-gnueabihf/bits/types/struct_FILE.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   struct _IO_codecvt *_codecvt ;
   struct _IO_wide_data *_wide_data ;
   struct _IO_FILE *_freeres_list ;
   void *_freeres_buf ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15U * sizeof(int ) - 4U * sizeof(void *)) - sizeof(size_t )] ;
};
#line 202 "/home/pi/crest/bin/../include/crest.h"
extern void __CrestInt(int *x )  __attribute__((__crest_skip__)) ;
#line 139 "/usr/include/stdio.h"
extern FILE *stderr ;
#line 326
extern int fprintf(FILE * __restrict  __stream , char const   * __restrict  __format 
                   , ...) ;
#line 332
extern int printf(char const   * __restrict  __format  , ...) ;
#line 15 "example1.c"
int main(void) 
{ 
  int a ;
  int b ;
  int c ;
  int i ;
  int __retres5 ;

  {
  __globinit_example1();
  __CrestCall(1, 1);
  __CrestLoad(2, (unsigned long )0, (long long )0);
  __CrestStore(3, (unsigned long )(& a));
#line 16
  a = 0;
  __CrestLoad(4, (unsigned long )0, (long long )0);
  __CrestStore(5, (unsigned long )(& b));
#line 16
  b = 0;
  __CrestLoad(6, (unsigned long )0, (long long )0);
  __CrestStore(7, (unsigned long )(& c));
#line 16
  c = 0;
  __CrestLoad(8, (unsigned long )0, (long long )0);
  __CrestStore(9, (unsigned long )(& i));
#line 18
  i = 0;
#line 18
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrestLoad(12, (unsigned long )(& i), (long long )i);
    __CrestLoad(11, (unsigned long )0, (long long )3);
    __CrestApply2(10, 16, (long long )(i < 3));
#line 18
    if (i < 3) {
      __CrestBranch(13, 6, 1);

    } else {
      __CrestBranch(14, 7, 0);
#line 18
      goto while_break;
    }
    }
#line 20
    __CrestInt(& a);
    __CrestLoad(15, (unsigned long )(& a), (long long )a);
#line 20
    fprintf((FILE * __restrict  )stderr, (char const   * __restrict  )"%d\n", a);
    __CrestClearStack(16);
#line 21
    __CrestInt(& b);
    __CrestLoad(17, (unsigned long )(& b), (long long )b);
#line 21
    fprintf((FILE * __restrict  )stderr, (char const   * __restrict  )"%d\n", b);
    __CrestClearStack(18);
    __CrestLoad(23, (unsigned long )0, (long long )3);
    __CrestLoad(22, (unsigned long )(& a), (long long )a);
    __CrestApply2(21, 2, (long long )(3 * a));
    __CrestLoad(20, (unsigned long )(& b), (long long )b);
    __CrestApply2(19, 0, (long long )(3 * a + b));
    __CrestStore(24, (unsigned long )(& c));
#line 23
    c = 3 * a + b;
    {
    __CrestLoad(27, (unsigned long )(& a), (long long )a);
    __CrestLoad(26, (unsigned long )0, (long long )0);
    __CrestApply2(25, 16, (long long )(a < 0));
#line 26
    if (a < 0) {
      __CrestBranch(28, 10, 1);
#line 27
      printf((char const   * __restrict  )"@L0");
      __CrestClearStack(30);
    } else {
      __CrestBranch(29, 11, 0);
      {
      __CrestLoad(33, (unsigned long )(& b), (long long )b);
      __CrestLoad(32, (unsigned long )0, (long long )8);
      __CrestApply2(31, 14, (long long )(b > 8));
#line 30
      if (b > 8) {
        __CrestBranch(34, 12, 1);
#line 31
        printf((char const   * __restrict  )"@L1");
        __CrestClearStack(36);
      } else {
        __CrestBranch(35, 13, 0);
        {
        __CrestLoad(39, (unsigned long )(& c), (long long )c);
        __CrestLoad(38, (unsigned long )0, (long long )0);
        __CrestApply2(37, 14, (long long )(c > 0));
#line 34
        if (c > 0) {
          __CrestBranch(40, 14, 1);
#line 35
          printf((char const   * __restrict  )"@L2");
          __CrestClearStack(42);
        } else {
          __CrestBranch(41, 15, 0);
          {
          __CrestLoad(47, (unsigned long )(& a), (long long )a);
          __CrestLoad(46, (unsigned long )(& b), (long long )b);
          __CrestApply2(45, 0, (long long )(a + b));
          __CrestLoad(44, (unsigned long )0, (long long )10);
          __CrestApply2(43, 16, (long long )(a + b < 10));
#line 38
          if (a + b < 10) {
            __CrestBranch(48, 16, 1);
#line 39
            printf((char const   * __restrict  )"@L3");
            __CrestClearStack(50);
          } else {
            __CrestBranch(49, 17, 0);
#line 42
            printf((char const   * __restrict  )"@L4");
            __CrestClearStack(51);
          }
          }
        }
        }
      }
      }
    }
    }
    __CrestLoad(54, (unsigned long )(& i), (long long )i);
    __CrestLoad(53, (unsigned long )0, (long long )1);
    __CrestApply2(52, 0, (long long )(i + 1));
    __CrestStore(55, (unsigned long )(& i));
#line 18
    i ++;
  }
  while_break: /* CIL Label */ 
#line 48
  printf((char const   * __restrict  )"\n");
  __CrestClearStack(56);
  __CrestLoad(57, (unsigned long )0, (long long )0);
  __CrestStore(58, (unsigned long )(& __retres5));
#line 49
  __retres5 = 0;
  __CrestLoad(59, (unsigned long )(& __retres5), (long long )__retres5);
  __CrestReturn(60);
#line 15
  return (__retres5);
}
}
void __globinit_example1(void) 
{ 


  {
  __CrestInit();
}
}
