/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 318 "btree.c"
void __globinit_btree(void) ;
extern void __CrestInit(void)  __attribute__((__crest_skip__)) ;
extern void __CrestHandleReturn(int id , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestReturn(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestCall(int id , unsigned int fid )  __attribute__((__crest_skip__)) ;
extern void __CrestBranch(int id , int bid , unsigned char b )  __attribute__((__crest_skip__)) ;
extern void __CrestApply2(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestApply1(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestClearStack(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestStore(int id , unsigned long addr )  __attribute__((__crest_skip__)) ;
extern void __CrestLoad(int id , unsigned long addr , long long val )  __attribute__((__crest_skip__)) ;
#line 46 "/usr/include/i386/_types.h"
typedef long long __int64_t;
#line 92 "/usr/include/i386/_types.h"
typedef unsigned long __darwin_size_t;
#line 71 "/usr/include/sys/_types.h"
typedef __int64_t __darwin_off_t;
#line 31 "/usr/include/sys/_types/_size_t.h"
typedef __darwin_size_t size_t;
#line 81 "/usr/include/_stdio.h"
typedef __darwin_off_t fpos_t;
#line 92 "/usr/include/_stdio.h"
struct __sbuf {
   unsigned char *_base ;
   int _size ;
};
#line 98
struct __sFILEX;
#line 98
struct __sFILEX;
#line 126 "/usr/include/_stdio.h"
struct __sFILE {
   unsigned char *_p ;
   int _r ;
   int _w ;
   short _flags ;
   short _file ;
   struct __sbuf _bf ;
   int _lbfsize ;
   void *_cookie ;
   int (*_close)(void * ) ;
   int (*_read)(void * , char * , int  ) ;
   fpos_t (*_seek)(void * , fpos_t  , int  ) ;
   int (*_write)(void * , char const   * , int  ) ;
   struct __sbuf _ub ;
   struct __sFILEX *_extra ;
   int _ur ;
   unsigned char _ubuf[3] ;
   unsigned char _nbuf[1] ;
   struct __sbuf _lb ;
   int _blksize ;
   fpos_t _offset ;
};
#line 126 "/usr/include/_stdio.h"
typedef struct __sFILE FILE;
#line 10 "btree.c"
struct btreeNode {
   int val[5] ;
   int count ;
   struct btreeNode *link[5] ;
};
#line 83 "/opt/local/lib/gcc5/gcc/x86_64-apple-darwin17/5.5.0/include-fixed/stdio.h"
extern FILE *__stderrp ;
#line 169
extern int ( /* format attribute */  fprintf)(FILE * __restrict   , char const   * __restrict   
                                              , ...) ;
#line 184
extern int ( /* format attribute */  printf)(char const   * __restrict    , ...) ;
#line 269
extern int __swbuf(int  , FILE * ) ;
#line 278 "/opt/local/lib/gcc5/gcc/x86_64-apple-darwin17/5.5.0/include-fixed/stdio.h"
__inline extern int __attribute__((__gnu_inline__))  ( __attribute__((__always_inline__)) __sputc)(int _c ,
                                                                                                   FILE *_p ) 
{ 
  unsigned char *tmp ;
  unsigned char tmp___0 ;
  int tmp___1 ;
  int __attribute__((__gnu_inline__))  __retres6 ;

  {
  __CrestCall(2, 1);
  __CrestStore(1, (unsigned long )(& _c));
  __CrestLoad(5, (unsigned long )(& _p->_w), (long long )_p->_w);
  __CrestLoad(4, (unsigned long )0, (long long )1);
  __CrestApply2(3, 1, (long long )(_p->_w - 1));
  __CrestStore(6, (unsigned long )(& _p->_w));
#line 279
  (_p->_w) --;
  {
  __CrestLoad(9, (unsigned long )(& _p->_w), (long long )_p->_w);
  __CrestLoad(8, (unsigned long )0, (long long )0);
  __CrestApply2(7, 17, (long long )(_p->_w >= 0));
#line 279
  if (_p->_w >= 0) {
    __CrestBranch(10, 3, 1);
#line 280
    tmp = _p->_p;
#line 280
    (_p->_p) ++;
    __CrestLoad(12, (unsigned long )(& _c), (long long )_c);
    __CrestStore(13, (unsigned long )(& tmp___0));
#line 280
    tmp___0 = (unsigned char )_c;
    __CrestLoad(14, (unsigned long )(& tmp___0), (long long )tmp___0);
    __CrestStore(15, (unsigned long )tmp);
#line 280
    *tmp = tmp___0;
    __CrestLoad(16, (unsigned long )(& tmp___0), (long long )tmp___0);
    __CrestStore(17, (unsigned long )(& __retres6));
#line 280
    __retres6 = (int __attribute__((__gnu_inline__))  )tmp___0;
#line 280
    goto return_label;
  } else {
    __CrestBranch(11, 6, 0);
    {
    __CrestLoad(20, (unsigned long )(& _p->_w), (long long )_p->_w);
    __CrestLoad(19, (unsigned long )(& _p->_lbfsize), (long long )_p->_lbfsize);
    __CrestApply2(18, 17, (long long )(_p->_w >= _p->_lbfsize));
#line 279
    if (_p->_w >= _p->_lbfsize) {
      __CrestBranch(21, 7, 1);
      {
      __CrestLoad(25, (unsigned long )(& _c), (long long )_c);
      __CrestLoad(24, (unsigned long )0, (long long )10);
      __CrestApply2(23, 13, (long long )((int )((char )_c) != 10));
#line 279
      if ((int )((char )_c) != 10) {
        __CrestBranch(26, 8, 1);
#line 280
        tmp = _p->_p;
#line 280
        (_p->_p) ++;
        __CrestLoad(28, (unsigned long )(& _c), (long long )_c);
        __CrestStore(29, (unsigned long )(& tmp___0));
#line 280
        tmp___0 = (unsigned char )_c;
        __CrestLoad(30, (unsigned long )(& tmp___0), (long long )tmp___0);
        __CrestStore(31, (unsigned long )tmp);
#line 280
        *tmp = tmp___0;
        __CrestLoad(32, (unsigned long )(& tmp___0), (long long )tmp___0);
        __CrestStore(33, (unsigned long )(& __retres6));
#line 280
        __retres6 = (int __attribute__((__gnu_inline__))  )tmp___0;
#line 280
        goto return_label;
      } else {
        __CrestBranch(27, 11, 0);
        __CrestLoad(34, (unsigned long )(& _c), (long long )_c);
#line 282
        tmp___1 = __swbuf(_c, _p);
        __CrestHandleReturn(36, (long long )tmp___1);
        __CrestStore(35, (unsigned long )(& tmp___1));
        __CrestLoad(37, (unsigned long )(& tmp___1), (long long )tmp___1);
        __CrestStore(38, (unsigned long )(& __retres6));
#line 282
        __retres6 = (int __attribute__((__gnu_inline__))  )tmp___1;
#line 282
        goto return_label;
      }
      }
    } else {
      __CrestBranch(22, 14, 0);
      __CrestLoad(39, (unsigned long )(& _c), (long long )_c);
#line 282
      tmp___1 = __swbuf(_c, _p);
      __CrestHandleReturn(41, (long long )tmp___1);
      __CrestStore(40, (unsigned long )(& tmp___1));
      __CrestLoad(42, (unsigned long )(& tmp___1), (long long )tmp___1);
      __CrestStore(43, (unsigned long )(& __retres6));
#line 282
      __retres6 = (int __attribute__((__gnu_inline__))  )tmp___1;
#line 282
      goto return_label;
    }
    }
  }
  }
  return_label: /* CIL Label */ 
  {
  __CrestLoad(44, (unsigned long )(& __retres6), (long long )__retres6);
  __CrestReturn(45);
#line 278
  return (__retres6);
  }
}
}
#line 150 "/usr/include/stdlib.h"
extern  __attribute__((__noreturn__)) void exit(int  ) ;
#line 151
extern void free(void * ) ;
#line 160
extern void *( __attribute__((__warn_unused_result__)) malloc)(size_t __size )  __attribute__((__alloc_size__(1))) ;
#line 202 "/Users/leemhyerin/Desktop/mi/crest/bin/../include/crest.h"
extern void __CrestInt(int *x )  __attribute__((__crest_skip__)) ;
#line 15 "btree.c"
struct btreeNode *root  ;
#line 18 "btree.c"
struct btreeNode *createNode(int val , struct btreeNode *child ) 
{ 
  struct btreeNode *newNode ;
  void *tmp ;

  {
  __CrestCall(47, 2);
  __CrestStore(46, (unsigned long )(& val));
  __CrestLoad(48, (unsigned long )0, (long long )sizeof(struct btreeNode ));
#line 20
  tmp = malloc(sizeof(struct btreeNode ));
  __CrestClearStack(49);
#line 20
  newNode = (struct btreeNode *)tmp;
  __CrestLoad(50, (unsigned long )(& val), (long long )val);
  __CrestStore(51, (unsigned long )(& newNode->val[1]));
#line 21
  newNode->val[1] = val;
  __CrestLoad(52, (unsigned long )0, (long long )1);
  __CrestStore(53, (unsigned long )(& newNode->count));
#line 22
  newNode->count = 1;
#line 23
  newNode->link[0] = root;
#line 24
  newNode->link[1] = child;
  {
  __CrestReturn(54);
#line 25
  return (newNode);
  }
}
}
#line 29 "btree.c"
void addValToNode(int val , int pos , struct btreeNode *node , struct btreeNode *child ) 
{ 
  int j ;

  {
  __CrestCall(57, 3);
  __CrestStore(56, (unsigned long )(& pos));
  __CrestStore(55, (unsigned long )(& val));
  __CrestLoad(58, (unsigned long )(& node->count), (long long )node->count);
  __CrestStore(59, (unsigned long )(& j));
#line 31
  j = node->count;
  {
#line 32
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrestLoad(62, (unsigned long )(& j), (long long )j);
    __CrestLoad(61, (unsigned long )(& pos), (long long )pos);
    __CrestApply2(60, 14, (long long )(j > pos));
#line 32
    if (j > pos) {
      __CrestBranch(63, 25, 1);

    } else {
      __CrestBranch(64, 26, 0);
#line 32
      goto while_break;
    }
    }
    __CrestLoad(65, (unsigned long )(& node->val[j]), (long long )node->val[j]);
    __CrestStore(66, (unsigned long )(& node->val[j + 1]));
#line 33
    node->val[j + 1] = node->val[j];
#line 34
    node->link[j + 1] = node->link[j];
    __CrestLoad(69, (unsigned long )(& j), (long long )j);
    __CrestLoad(68, (unsigned long )0, (long long )1);
    __CrestApply2(67, 1, (long long )(j - 1));
    __CrestStore(70, (unsigned long )(& j));
#line 35
    j --;
  }
  while_break: /* CIL Label */ ;
  }
  __CrestLoad(71, (unsigned long )(& val), (long long )val);
  __CrestStore(72, (unsigned long )(& node->val[j + 1]));
#line 37
  node->val[j + 1] = val;
#line 38
  node->link[j + 1] = child;
  __CrestLoad(75, (unsigned long )(& node->count), (long long )node->count);
  __CrestLoad(74, (unsigned long )0, (long long )1);
  __CrestApply2(73, 0, (long long )(node->count + 1));
  __CrestStore(76, (unsigned long )(& node->count));
#line 39
  (node->count) ++;

  {
  __CrestReturn(77);
#line 29
  return;
  }
}
}
#line 43 "btree.c"
void splitNode(int val , int *pval , int pos , struct btreeNode *node , struct btreeNode *child ,
               struct btreeNode **newNode ) 
{ 
  int median ;
  int j ;
  void *tmp ;
  struct btreeNode *mem_10 ;
  struct btreeNode *mem_11 ;
  struct btreeNode *mem_12 ;
  struct btreeNode *mem_13 ;

  {
  __CrestCall(80, 4);
  __CrestStore(79, (unsigned long )(& pos));
  __CrestStore(78, (unsigned long )(& val));
  {
  __CrestLoad(83, (unsigned long )(& pos), (long long )pos);
  __CrestLoad(82, (unsigned long )0, (long long )2);
  __CrestApply2(81, 14, (long long )(pos > 2));
#line 47
  if (pos > 2) {
    __CrestBranch(84, 33, 1);
    __CrestLoad(86, (unsigned long )0, (long long )3);
    __CrestStore(87, (unsigned long )(& median));
#line 48
    median = 3;
  } else {
    __CrestBranch(85, 34, 0);
    __CrestLoad(88, (unsigned long )0, (long long )2);
    __CrestStore(89, (unsigned long )(& median));
#line 50
    median = 2;
  }
  }
  __CrestLoad(90, (unsigned long )0, (long long )sizeof(struct btreeNode ));
#line 52
  tmp = malloc(sizeof(struct btreeNode ));
  __CrestClearStack(91);
#line 52
  *newNode = (struct btreeNode *)tmp;
  __CrestLoad(94, (unsigned long )(& median), (long long )median);
  __CrestLoad(93, (unsigned long )0, (long long )1);
  __CrestApply2(92, 0, (long long )(median + 1));
  __CrestStore(95, (unsigned long )(& j));
#line 53
  j = median + 1;
  {
#line 54
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrestLoad(98, (unsigned long )(& j), (long long )j);
    __CrestLoad(97, (unsigned long )0, (long long )4);
    __CrestApply2(96, 15, (long long )(j <= 4));
#line 54
    if (j <= 4) {
      __CrestBranch(99, 40, 1);

    } else {
      __CrestBranch(100, 41, 0);
#line 54
      goto while_break;
    }
    }
#line 55
    mem_10 = *newNode;
    __CrestLoad(101, (unsigned long )(& node->val[j]), (long long )node->val[j]);
    __CrestStore(102, (unsigned long )(& mem_10->val[j - median]));
#line 55
    mem_10->val[j - median] = node->val[j];
#line 56
    mem_11 = *newNode;
#line 56
    mem_11->link[j - median] = node->link[j];
    __CrestLoad(105, (unsigned long )(& j), (long long )j);
    __CrestLoad(104, (unsigned long )0, (long long )1);
    __CrestApply2(103, 0, (long long )(j + 1));
    __CrestStore(106, (unsigned long )(& j));
#line 57
    j ++;
  }
  while_break: /* CIL Label */ ;
  }
  __CrestLoad(107, (unsigned long )(& median), (long long )median);
  __CrestStore(108, (unsigned long )(& node->count));
#line 59
  node->count = median;
#line 60
  mem_12 = *newNode;
  __CrestLoad(111, (unsigned long )0, (long long )4);
  __CrestLoad(110, (unsigned long )(& median), (long long )median);
  __CrestApply2(109, 1, (long long )(4 - median));
  __CrestStore(112, (unsigned long )(& mem_12->count));
#line 60
  mem_12->count = 4 - median;
  {
  __CrestLoad(115, (unsigned long )(& pos), (long long )pos);
  __CrestLoad(114, (unsigned long )0, (long long )2);
  __CrestApply2(113, 15, (long long )(pos <= 2));
#line 62
  if (pos <= 2) {
    __CrestBranch(116, 46, 1);
    __CrestLoad(118, (unsigned long )(& val), (long long )val);
    __CrestLoad(119, (unsigned long )(& pos), (long long )pos);
#line 63
    addValToNode(val, pos, node, child);
    __CrestClearStack(120);
  } else {
    __CrestBranch(117, 47, 0);
    __CrestLoad(121, (unsigned long )(& val), (long long )val);
    __CrestLoad(124, (unsigned long )(& pos), (long long )pos);
    __CrestLoad(123, (unsigned long )(& median), (long long )median);
    __CrestApply2(122, 1, (long long )(pos - median));
#line 65
    addValToNode(val, pos - median, *newNode, child);
    __CrestClearStack(125);
  }
  }
  __CrestLoad(126, (unsigned long )(& node->val[node->count]), (long long )node->val[node->count]);
  __CrestStore(127, (unsigned long )pval);
#line 67
  *pval = node->val[node->count];
#line 68
  mem_13 = *newNode;
#line 68
  mem_13->link[0] = node->link[node->count];
  __CrestLoad(130, (unsigned long )(& node->count), (long long )node->count);
  __CrestLoad(129, (unsigned long )0, (long long )1);
  __CrestApply2(128, 1, (long long )(node->count - 1));
  __CrestStore(131, (unsigned long )(& node->count));
#line 69
  (node->count) --;

  {
  __CrestReturn(132);
#line 43
  return;
  }
}
}
#line 73 "btree.c"
int setValueInNode(int val , int *pval , struct btreeNode *node , struct btreeNode **child ) 
{ 
  int pos ;
  int tmp ;
  int __retres7 ;

  {
  __CrestCall(134, 5);
  __CrestStore(133, (unsigned long )(& val));
  {
  __CrestLoad(137, (unsigned long )(& node), (long long )((unsigned long )node));
  __CrestLoad(136, (unsigned long )0, (long long )0);
  __CrestApply2(135, 12, (long long )(node == 0));
#line 77
  if (node == 0) {
    __CrestBranch(138, 52, 1);
    __CrestLoad(140, (unsigned long )(& val), (long long )val);
    __CrestStore(141, (unsigned long )pval);
#line 78
    *pval = val;
#line 79
    *child = (struct btreeNode *)((void *)0);
    __CrestLoad(142, (unsigned long )0, (long long )1);
    __CrestStore(143, (unsigned long )(& __retres7));
#line 80
    __retres7 = 1;
#line 80
    goto return_label;
  } else {
    __CrestBranch(139, 55, 0);

  }
  }
  {
  __CrestLoad(146, (unsigned long )(& val), (long long )val);
  __CrestLoad(145, (unsigned long )(& node->val[1]), (long long )node->val[1]);
  __CrestApply2(144, 16, (long long )(val < node->val[1]));
#line 83
  if (val < node->val[1]) {
    __CrestBranch(147, 57, 1);
    __CrestLoad(149, (unsigned long )0, (long long )0);
    __CrestStore(150, (unsigned long )(& pos));
#line 84
    pos = 0;
  } else {
    __CrestBranch(148, 58, 0);
    __CrestLoad(151, (unsigned long )(& node->count), (long long )node->count);
    __CrestStore(152, (unsigned long )(& pos));
#line 86
    pos = node->count;
    {
#line 86
    while (1) {
      while_continue: /* CIL Label */ ;
      {
      __CrestLoad(155, (unsigned long )(& val), (long long )val);
      __CrestLoad(154, (unsigned long )(& node->val[pos]), (long long )node->val[pos]);
      __CrestApply2(153, 16, (long long )(val < node->val[pos]));
#line 86
      if (val < node->val[pos]) {
        __CrestBranch(156, 63, 1);
        {
        __CrestLoad(160, (unsigned long )(& pos), (long long )pos);
        __CrestLoad(159, (unsigned long )0, (long long )1);
        __CrestApply2(158, 14, (long long )(pos > 1));
#line 86
        if (pos > 1) {
          __CrestBranch(161, 64, 1);

        } else {
          __CrestBranch(162, 65, 0);
#line 86
          goto while_break;
        }
        }
      } else {
        __CrestBranch(157, 66, 0);
#line 86
        goto while_break;
      }
      }
      __CrestLoad(165, (unsigned long )(& pos), (long long )pos);
      __CrestLoad(164, (unsigned long )0, (long long )1);
      __CrestApply2(163, 1, (long long )(pos - 1));
      __CrestStore(166, (unsigned long )(& pos));
#line 86
      pos --;
    }
    while_break: /* CIL Label */ ;
    }
    {
    __CrestLoad(169, (unsigned long )(& val), (long long )val);
    __CrestLoad(168, (unsigned long )(& node->val[pos]), (long long )node->val[pos]);
    __CrestApply2(167, 12, (long long )(val == node->val[pos]));
#line 88
    if (val == node->val[pos]) {
      __CrestBranch(170, 70, 1);
#line 89
      printf((char const   * __restrict  )"Duplicates not allowed\n");
      __CrestClearStack(172);
      __CrestLoad(173, (unsigned long )0, (long long )0);
      __CrestStore(174, (unsigned long )(& __retres7));
#line 90
      __retres7 = 0;
#line 90
      goto return_label;
    } else {
      __CrestBranch(171, 73, 0);

    }
    }
  }
  }
  __CrestLoad(175, (unsigned long )(& val), (long long )val);
#line 93
  tmp = setValueInNode(val, pval, node->link[pos], child);
  __CrestHandleReturn(177, (long long )tmp);
  __CrestStore(176, (unsigned long )(& tmp));
  {
  __CrestLoad(180, (unsigned long )(& tmp), (long long )tmp);
  __CrestLoad(179, (unsigned long )0, (long long )0);
  __CrestApply2(178, 13, (long long )(tmp != 0));
#line 93
  if (tmp != 0) {
    __CrestBranch(181, 76, 1);
    {
    __CrestLoad(185, (unsigned long )(& node->count), (long long )node->count);
    __CrestLoad(184, (unsigned long )0, (long long )4);
    __CrestApply2(183, 16, (long long )(node->count < 4));
#line 94
    if (node->count < 4) {
      __CrestBranch(186, 77, 1);
      __CrestLoad(188, (unsigned long )pval, (long long )*pval);
      __CrestLoad(189, (unsigned long )(& pos), (long long )pos);
#line 95
      addValToNode(*pval, pos, node, *child);
      __CrestClearStack(190);
    } else {
      __CrestBranch(187, 78, 0);
      __CrestLoad(191, (unsigned long )pval, (long long )*pval);
      __CrestLoad(192, (unsigned long )(& pos), (long long )pos);
#line 97
      splitNode(*pval, pval, pos, node, *child, child);
      __CrestClearStack(193);
      __CrestLoad(194, (unsigned long )0, (long long )1);
      __CrestStore(195, (unsigned long )(& __retres7));
#line 98
      __retres7 = 1;
#line 98
      goto return_label;
    }
    }
  } else {
    __CrestBranch(182, 81, 0);

  }
  }
  __CrestLoad(196, (unsigned long )0, (long long )0);
  __CrestStore(197, (unsigned long )(& __retres7));
#line 101
  __retres7 = 0;
  return_label: /* CIL Label */ 
  {
  __CrestLoad(198, (unsigned long )(& __retres7), (long long )__retres7);
  __CrestReturn(199);
#line 73
  return (__retres7);
  }
}
}
#line 105 "btree.c"
void insertion(int val ) 
{ 
  int flag ;
  int i ;
  struct btreeNode *child ;

  {
  __CrestCall(201, 6);
  __CrestStore(200, (unsigned long )(& val));
  __CrestLoad(202, (unsigned long )(& val), (long long )val);
#line 109
  flag = setValueInNode(val, & i, root, & child);
  __CrestHandleReturn(204, (long long )flag);
  __CrestStore(203, (unsigned long )(& flag));
  {
  __CrestLoad(207, (unsigned long )(& flag), (long long )flag);
  __CrestLoad(206, (unsigned long )0, (long long )0);
  __CrestApply2(205, 13, (long long )(flag != 0));
#line 110
  if (flag != 0) {
    __CrestBranch(208, 86, 1);
    __CrestLoad(210, (unsigned long )(& i), (long long )i);
#line 111
    root = createNode(i, child);
    __CrestClearStack(211);
  } else {
    __CrestBranch(209, 87, 0);

  }
  }

  {
  __CrestReturn(212);
#line 105
  return;
  }
}
}
#line 115 "btree.c"
void copySuccessor(struct btreeNode *myNode , int pos ) 
{ 
  struct btreeNode *dummy ;

  {
  __CrestCall(214, 7);
  __CrestStore(213, (unsigned long )(& pos));
#line 117
  dummy = myNode->link[pos];
  {
#line 119
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrestLoad(217, (unsigned long )(& dummy->link[0]), (long long )((unsigned long )dummy->link[0]));
    __CrestLoad(216, (unsigned long )0, (long long )((unsigned long )((void *)0)));
    __CrestApply2(215, 13, (long long )((unsigned long )dummy->link[0] != (unsigned long )((void *)0)));
#line 119
    if ((unsigned long )dummy->link[0] != (unsigned long )((void *)0)) {
      __CrestBranch(218, 95, 1);

    } else {
      __CrestBranch(219, 96, 0);
#line 119
      goto while_break;
    }
    }
#line 120
    dummy = dummy->link[0];
  }
  while_break: /* CIL Label */ ;
  }
  __CrestLoad(220, (unsigned long )(& dummy->val[1]), (long long )dummy->val[1]);
  __CrestStore(221, (unsigned long )(& myNode->val[pos]));
#line 121
  myNode->val[pos] = dummy->val[1];

  {
  __CrestReturn(222);
#line 115
  return;
  }
}
}
#line 126 "btree.c"
void removeVal(struct btreeNode *myNode , int pos ) 
{ 
  int i ;

  {
  __CrestCall(224, 8);
  __CrestStore(223, (unsigned long )(& pos));
  __CrestLoad(227, (unsigned long )(& pos), (long long )pos);
  __CrestLoad(226, (unsigned long )0, (long long )1);
  __CrestApply2(225, 0, (long long )(pos + 1));
  __CrestStore(228, (unsigned long )(& i));
#line 127
  i = pos + 1;
  {
#line 128
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrestLoad(231, (unsigned long )(& i), (long long )i);
    __CrestLoad(230, (unsigned long )(& myNode->count), (long long )myNode->count);
    __CrestApply2(229, 15, (long long )(i <= myNode->count));
#line 128
    if (i <= myNode->count) {
      __CrestBranch(232, 107, 1);

    } else {
      __CrestBranch(233, 108, 0);
#line 128
      goto while_break;
    }
    }
    __CrestLoad(234, (unsigned long )(& myNode->val[i]), (long long )myNode->val[i]);
    __CrestStore(235, (unsigned long )(& myNode->val[i - 1]));
#line 129
    myNode->val[i - 1] = myNode->val[i];
#line 130
    myNode->link[i - 1] = myNode->link[i];
    __CrestLoad(238, (unsigned long )(& i), (long long )i);
    __CrestLoad(237, (unsigned long )0, (long long )1);
    __CrestApply2(236, 0, (long long )(i + 1));
    __CrestStore(239, (unsigned long )(& i));
#line 131
    i ++;
  }
  while_break: /* CIL Label */ ;
  }
  __CrestLoad(242, (unsigned long )(& myNode->count), (long long )myNode->count);
  __CrestLoad(241, (unsigned long )0, (long long )1);
  __CrestApply2(240, 1, (long long )(myNode->count - 1));
  __CrestStore(243, (unsigned long )(& myNode->count));
#line 133
  (myNode->count) --;

  {
  __CrestReturn(244);
#line 126
  return;
  }
}
}
#line 137 "btree.c"
void doRightShift(struct btreeNode *myNode , int pos ) 
{ 
  struct btreeNode *x ;
  int j ;

  {
  __CrestCall(246, 9);
  __CrestStore(245, (unsigned long )(& pos));
#line 138
  x = myNode->link[pos];
  __CrestLoad(247, (unsigned long )(& x->count), (long long )x->count);
  __CrestStore(248, (unsigned long )(& j));
#line 139
  j = x->count;
  {
#line 141
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrestLoad(251, (unsigned long )(& j), (long long )j);
    __CrestLoad(250, (unsigned long )0, (long long )0);
    __CrestApply2(249, 14, (long long )(j > 0));
#line 141
    if (j > 0) {
      __CrestBranch(252, 119, 1);

    } else {
      __CrestBranch(253, 120, 0);
#line 141
      goto while_break;
    }
    }
    __CrestLoad(254, (unsigned long )(& x->val[j]), (long long )x->val[j]);
    __CrestStore(255, (unsigned long )(& x->val[j + 1]));
#line 142
    x->val[j + 1] = x->val[j];
#line 143
    x->link[j + 1] = x->link[j];
  }
  while_break: /* CIL Label */ ;
  }
  __CrestLoad(256, (unsigned long )(& myNode->val[pos]), (long long )myNode->val[pos]);
  __CrestStore(257, (unsigned long )(& x->val[1]));
#line 145
  x->val[1] = myNode->val[pos];
#line 146
  x->link[1] = x->link[0];
  __CrestLoad(260, (unsigned long )(& x->count), (long long )x->count);
  __CrestLoad(259, (unsigned long )0, (long long )1);
  __CrestApply2(258, 0, (long long )(x->count + 1));
  __CrestStore(261, (unsigned long )(& x->count));
#line 147
  (x->count) ++;
#line 149
  x = myNode->link[pos - 1];
  __CrestLoad(262, (unsigned long )(& x->val[x->count]), (long long )x->val[x->count]);
  __CrestStore(263, (unsigned long )(& myNode->val[pos]));
#line 150
  myNode->val[pos] = x->val[x->count];
#line 151
  myNode->link[pos] = x->link[x->count];
  __CrestLoad(266, (unsigned long )(& x->count), (long long )x->count);
  __CrestLoad(265, (unsigned long )0, (long long )1);
  __CrestApply2(264, 1, (long long )(x->count - 1));
  __CrestStore(267, (unsigned long )(& x->count));
#line 152
  (x->count) --;

  {
  __CrestReturn(268);
#line 137
  return;
  }
}
}
#line 157 "btree.c"
void doLeftShift(struct btreeNode *myNode , int pos ) 
{ 
  int j ;
  struct btreeNode *x ;
  struct btreeNode *mem_5 ;

  {
  __CrestCall(270, 10);
  __CrestStore(269, (unsigned long )(& pos));
  __CrestLoad(271, (unsigned long )0, (long long )1);
  __CrestStore(272, (unsigned long )(& j));
#line 158
  j = 1;
#line 159
  x = myNode->link[pos - 1];
  __CrestLoad(275, (unsigned long )(& x->count), (long long )x->count);
  __CrestLoad(274, (unsigned long )0, (long long )1);
  __CrestApply2(273, 0, (long long )(x->count + 1));
  __CrestStore(276, (unsigned long )(& x->count));
#line 161
  (x->count) ++;
  __CrestLoad(277, (unsigned long )(& myNode->val[pos]), (long long )myNode->val[pos]);
  __CrestStore(278, (unsigned long )(& x->val[x->count]));
#line 162
  x->val[x->count] = myNode->val[pos];
#line 163
  mem_5 = myNode->link[pos];
#line 163
  x->link[x->count] = mem_5->link[0];
#line 165
  x = myNode->link[pos];
  __CrestLoad(279, (unsigned long )(& x->val[1]), (long long )x->val[1]);
  __CrestStore(280, (unsigned long )(& myNode->val[pos]));
#line 166
  myNode->val[pos] = x->val[1];
#line 167
  x->link[0] = x->link[1];
  __CrestLoad(283, (unsigned long )(& x->count), (long long )x->count);
  __CrestLoad(282, (unsigned long )0, (long long )1);
  __CrestApply2(281, 1, (long long )(x->count - 1));
  __CrestStore(284, (unsigned long )(& x->count));
#line 168
  (x->count) --;
  {
#line 170
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrestLoad(287, (unsigned long )(& j), (long long )j);
    __CrestLoad(286, (unsigned long )(& x->count), (long long )x->count);
    __CrestApply2(285, 15, (long long )(j <= x->count));
#line 170
    if (j <= x->count) {
      __CrestBranch(288, 131, 1);

    } else {
      __CrestBranch(289, 132, 0);
#line 170
      goto while_break;
    }
    }
    __CrestLoad(290, (unsigned long )(& x->val[j + 1]), (long long )x->val[j + 1]);
    __CrestStore(291, (unsigned long )(& x->val[j]));
#line 171
    x->val[j] = x->val[j + 1];
#line 172
    x->link[j] = x->link[j + 1];
    __CrestLoad(294, (unsigned long )(& j), (long long )j);
    __CrestLoad(293, (unsigned long )0, (long long )1);
    __CrestApply2(292, 0, (long long )(j + 1));
    __CrestStore(295, (unsigned long )(& j));
#line 173
    j ++;
  }
  while_break: /* CIL Label */ ;
  }

  {
  __CrestReturn(296);
#line 157
  return;
  }
}
}
#line 179 "btree.c"
void mergeNodes(struct btreeNode *myNode , int pos ) 
{ 
  int j ;
  struct btreeNode *x1 ;
  struct btreeNode *x2 ;

  {
  __CrestCall(298, 11);
  __CrestStore(297, (unsigned long )(& pos));
  __CrestLoad(299, (unsigned long )0, (long long )1);
  __CrestStore(300, (unsigned long )(& j));
#line 180
  j = 1;
#line 181
  x1 = myNode->link[pos];
#line 181
  x2 = myNode->link[pos - 1];
  __CrestLoad(303, (unsigned long )(& x2->count), (long long )x2->count);
  __CrestLoad(302, (unsigned long )0, (long long )1);
  __CrestApply2(301, 0, (long long )(x2->count + 1));
  __CrestStore(304, (unsigned long )(& x2->count));
#line 183
  (x2->count) ++;
  __CrestLoad(305, (unsigned long )(& myNode->val[pos]), (long long )myNode->val[pos]);
  __CrestStore(306, (unsigned long )(& x2->val[x2->count]));
#line 184
  x2->val[x2->count] = myNode->val[pos];
#line 185
  x2->link[x2->count] = myNode->link[0];
  {
#line 187
  while (1) {
    while_continue: /* CIL Label */ ;
    {
    __CrestLoad(309, (unsigned long )(& j), (long long )j);
    __CrestLoad(308, (unsigned long )(& x1->count), (long long )x1->count);
    __CrestApply2(307, 15, (long long )(j <= x1->count));
#line 187
    if (j <= x1->count) {
      __CrestBranch(310, 142, 1);

    } else {
      __CrestBranch(311, 143, 0);
#line 187
      goto while_break;
    }
    }
    __CrestLoad(314, (unsigned long )(& x2->count), (long long )x2->count);
    __CrestLoad(313, (unsigned long )0, (long long )1);
    __CrestApply2(312, 0, (long long )(x2->count + 1));
    __CrestStore(315, (unsigned long )(& x2->count));
#line 188
    (x2->count) ++;
    __CrestLoad(316, (unsigned long )(& x1->val[j]), (long long )x1->val[j]);
    __CrestStore(317, (unsigned long )(& x2->val[x2->count]));
#line 189
    x2->val[x2->count] = x1->val[j];
#line 190
    x2->link[x2->count] = x1->link[j];
    __CrestLoad(320, (unsigned long )(& j), (long long )j);
    __CrestLoad(319, (unsigned long )0, (long long )1);
    __CrestApply2(318, 0, (long long )(j + 1));
    __CrestStore(321, (unsigned long )(& j));
#line 191
    j ++;
  }
  while_break: /* CIL Label */ ;
  }
  __CrestLoad(322, (unsigned long )(& pos), (long long )pos);
  __CrestStore(323, (unsigned long )(& j));
#line 194
  j = pos;
  {
#line 195
  while (1) {
    while_continue___0: /* CIL Label */ ;
    {
    __CrestLoad(326, (unsigned long )(& j), (long long )j);
    __CrestLoad(325, (unsigned long )(& myNode->count), (long long )myNode->count);
    __CrestApply2(324, 16, (long long )(j < myNode->count));
#line 195
    if (j < myNode->count) {
      __CrestBranch(327, 151, 1);

    } else {
      __CrestBranch(328, 152, 0);
#line 195
      goto while_break___0;
    }
    }
    __CrestLoad(329, (unsigned long )(& myNode->val[j + 1]), (long long )myNode->val[j + 1]);
    __CrestStore(330, (unsigned long )(& myNode->val[j]));
#line 196
    myNode->val[j] = myNode->val[j + 1];
#line 197
    myNode->link[j] = myNode->link[j + 1];
    __CrestLoad(333, (unsigned long )(& j), (long long )j);
    __CrestLoad(332, (unsigned long )0, (long long )1);
    __CrestApply2(331, 0, (long long )(j + 1));
    __CrestStore(334, (unsigned long )(& j));
#line 198
    j ++;
  }
  while_break___0: /* CIL Label */ ;
  }
  __CrestLoad(337, (unsigned long )(& myNode->count), (long long )myNode->count);
  __CrestLoad(336, (unsigned long )0, (long long )1);
  __CrestApply2(335, 1, (long long )(myNode->count - 1));
  __CrestStore(338, (unsigned long )(& myNode->count));
#line 200
  (myNode->count) --;
#line 201
  free((void *)x1);
  __CrestClearStack(339);

  {
  __CrestReturn(340);
#line 179
  return;
  }
}
}
#line 205 "btree.c"
void adjustNode(struct btreeNode *myNode , int pos ) 
{ 
  struct btreeNode *mem_3 ;
  struct btreeNode *mem_4 ;
  struct btreeNode *mem_5 ;
  struct btreeNode *mem_6 ;

  {
  __CrestCall(342, 12);
  __CrestStore(341, (unsigned long )(& pos));
  {
  __CrestLoad(345, (unsigned long )(& pos), (long long )pos);
  __CrestLoad(344, (unsigned long )0, (long long )0);
  __CrestApply2(343, 12, (long long )(pos == 0));
#line 206
  if (pos == 0) {
    __CrestBranch(346, 159, 1);
    {
#line 207
    mem_3 = myNode->link[1];
    {
    __CrestLoad(350, (unsigned long )(& mem_3->count), (long long )mem_3->count);
    __CrestLoad(349, (unsigned long )0, (long long )2);
    __CrestApply2(348, 14, (long long )(mem_3->count > 2));
#line 207
    if (mem_3->count > 2) {
      __CrestBranch(351, 162, 1);
      __CrestLoad(353, (unsigned long )0, (long long )1);
#line 208
      doLeftShift(myNode, 1);
      __CrestClearStack(354);
    } else {
      __CrestBranch(352, 163, 0);
      __CrestLoad(355, (unsigned long )0, (long long )1);
#line 210
      mergeNodes(myNode, 1);
      __CrestClearStack(356);
    }
    }
    }
  } else {
    __CrestBranch(347, 164, 0);
    {
    __CrestLoad(359, (unsigned long )(& myNode->count), (long long )myNode->count);
    __CrestLoad(358, (unsigned long )(& pos), (long long )pos);
    __CrestApply2(357, 13, (long long )(myNode->count != pos));
#line 213
    if (myNode->count != pos) {
      __CrestBranch(360, 165, 1);
      {
#line 214
      mem_4 = myNode->link[pos - 1];
      {
      __CrestLoad(364, (unsigned long )(& mem_4->count), (long long )mem_4->count);
      __CrestLoad(363, (unsigned long )0, (long long )2);
      __CrestApply2(362, 14, (long long )(mem_4->count > 2));
#line 214
      if (mem_4->count > 2) {
        __CrestBranch(365, 168, 1);
        __CrestLoad(367, (unsigned long )(& pos), (long long )pos);
#line 215
        doRightShift(myNode, pos);
        __CrestClearStack(368);
      } else {
        __CrestBranch(366, 169, 0);
        {
#line 217
        mem_5 = myNode->link[pos + 1];
        {
        __CrestLoad(371, (unsigned long )(& mem_5->count), (long long )mem_5->count);
        __CrestLoad(370, (unsigned long )0, (long long )2);
        __CrestApply2(369, 14, (long long )(mem_5->count > 2));
#line 217
        if (mem_5->count > 2) {
          __CrestBranch(372, 172, 1);
          __CrestLoad(376, (unsigned long )(& pos), (long long )pos);
          __CrestLoad(375, (unsigned long )0, (long long )1);
          __CrestApply2(374, 0, (long long )(pos + 1));
#line 218
          doLeftShift(myNode, pos + 1);
          __CrestClearStack(377);
        } else {
          __CrestBranch(373, 173, 0);
          __CrestLoad(378, (unsigned long )(& pos), (long long )pos);
#line 220
          mergeNodes(myNode, pos);
          __CrestClearStack(379);
        }
        }
        }
      }
      }
      }
    } else {
      __CrestBranch(361, 174, 0);
      {
#line 224
      mem_6 = myNode->link[pos - 1];
      {
      __CrestLoad(382, (unsigned long )(& mem_6->count), (long long )mem_6->count);
      __CrestLoad(381, (unsigned long )0, (long long )2);
      __CrestApply2(380, 14, (long long )(mem_6->count > 2));
#line 224
      if (mem_6->count > 2) {
        __CrestBranch(383, 177, 1);
        __CrestLoad(385, (unsigned long )(& pos), (long long )pos);
#line 225
        doRightShift(myNode, pos);
        __CrestClearStack(386);
      } else {
        __CrestBranch(384, 178, 0);
        __CrestLoad(387, (unsigned long )(& pos), (long long )pos);
#line 227
        mergeNodes(myNode, pos);
        __CrestClearStack(388);
      }
      }
      }
    }
    }
  }
  }

  {
  __CrestReturn(389);
#line 205
  return;
  }
}
}
#line 233 "btree.c"
int delValFromNode(int val , struct btreeNode *myNode ) 
{ 
  int pos ;
  int flag ;
  struct btreeNode *mem_5 ;

  {
  __CrestCall(391, 13);
  __CrestStore(390, (unsigned long )(& val));
  __CrestLoad(392, (unsigned long )0, (long long )0);
  __CrestStore(393, (unsigned long )(& flag));
#line 234
  flag = 0;
  {
  __CrestLoad(396, (unsigned long )(& myNode), (long long )((unsigned long )myNode));
  __CrestLoad(395, (unsigned long )0, (long long )0);
  __CrestApply2(394, 13, (long long )(myNode != 0));
#line 235
  if (myNode != 0) {
    __CrestBranch(397, 183, 1);
    {
    __CrestLoad(401, (unsigned long )(& val), (long long )val);
    __CrestLoad(400, (unsigned long )(& myNode->val[1]), (long long )myNode->val[1]);
    __CrestApply2(399, 16, (long long )(val < myNode->val[1]));
#line 236
    if (val < myNode->val[1]) {
      __CrestBranch(402, 184, 1);
      __CrestLoad(404, (unsigned long )0, (long long )0);
      __CrestStore(405, (unsigned long )(& pos));
#line 237
      pos = 0;
      __CrestLoad(406, (unsigned long )0, (long long )0);
      __CrestStore(407, (unsigned long )(& flag));
#line 238
      flag = 0;
    } else {
      __CrestBranch(403, 185, 0);
      __CrestLoad(408, (unsigned long )(& myNode->count), (long long )myNode->count);
      __CrestStore(409, (unsigned long )(& pos));
#line 240
      pos = myNode->count;
      {
#line 240
      while (1) {
        while_continue: /* CIL Label */ ;
        {
        __CrestLoad(412, (unsigned long )(& val), (long long )val);
        __CrestLoad(411, (unsigned long )(& myNode->val[pos]), (long long )myNode->val[pos]);
        __CrestApply2(410, 16, (long long )(val < myNode->val[pos]));
#line 240
        if (val < myNode->val[pos]) {
          __CrestBranch(413, 190, 1);
          {
          __CrestLoad(417, (unsigned long )(& pos), (long long )pos);
          __CrestLoad(416, (unsigned long )0, (long long )1);
          __CrestApply2(415, 14, (long long )(pos > 1));
#line 240
          if (pos > 1) {
            __CrestBranch(418, 191, 1);

          } else {
            __CrestBranch(419, 192, 0);
#line 240
            goto while_break;
          }
          }
        } else {
          __CrestBranch(414, 193, 0);
#line 240
          goto while_break;
        }
        }
        __CrestLoad(422, (unsigned long )(& pos), (long long )pos);
        __CrestLoad(421, (unsigned long )0, (long long )1);
        __CrestApply2(420, 1, (long long )(pos - 1));
        __CrestStore(423, (unsigned long )(& pos));
#line 240
        pos --;
      }
      while_break: /* CIL Label */ ;
      }
      {
      __CrestLoad(426, (unsigned long )(& val), (long long )val);
      __CrestLoad(425, (unsigned long )(& myNode->val[pos]), (long long )myNode->val[pos]);
      __CrestApply2(424, 12, (long long )(val == myNode->val[pos]));
#line 242
      if (val == myNode->val[pos]) {
        __CrestBranch(427, 197, 1);
        __CrestLoad(429, (unsigned long )0, (long long )1);
        __CrestStore(430, (unsigned long )(& flag));
#line 243
        flag = 1;
      } else {
        __CrestBranch(428, 198, 0);
        __CrestLoad(431, (unsigned long )0, (long long )0);
        __CrestStore(432, (unsigned long )(& flag));
#line 245
        flag = 0;
      }
      }
    }
    }
    {
    __CrestLoad(435, (unsigned long )(& flag), (long long )flag);
    __CrestLoad(434, (unsigned long )0, (long long )0);
    __CrestApply2(433, 13, (long long )(flag != 0));
#line 248
    if (flag != 0) {
      __CrestBranch(436, 200, 1);
      {
      __CrestLoad(440, (unsigned long )(& myNode->link[pos - 1]), (long long )((unsigned long )myNode->link[pos - 1]));
      __CrestLoad(439, (unsigned long )0, (long long )0);
      __CrestApply2(438, 13, (long long )(myNode->link[pos - 1] != 0));
#line 249
      if (myNode->link[pos - 1] != 0) {
        __CrestBranch(441, 201, 1);
        __CrestLoad(443, (unsigned long )(& pos), (long long )pos);
#line 250
        copySuccessor(myNode, pos);
        __CrestClearStack(444);
        __CrestLoad(445, (unsigned long )(& myNode->val[pos]), (long long )myNode->val[pos]);
#line 251
        flag = delValFromNode(myNode->val[pos], myNode->link[pos]);
        __CrestHandleReturn(447, (long long )flag);
        __CrestStore(446, (unsigned long )(& flag));
        {
        __CrestLoad(450, (unsigned long )(& flag), (long long )flag);
        __CrestLoad(449, (unsigned long )0, (long long )0);
        __CrestApply2(448, 12, (long long )(flag == 0));
#line 252
        if (flag == 0) {
          __CrestBranch(451, 203, 1);
#line 253
          printf((char const   * __restrict  )"Given data is not present in B-Tree\n");
          __CrestClearStack(453);
        } else {
          __CrestBranch(452, 204, 0);

        }
        }
      } else {
        __CrestBranch(442, 205, 0);
        __CrestLoad(454, (unsigned long )(& pos), (long long )pos);
#line 256
        removeVal(myNode, pos);
        __CrestClearStack(455);
      }
      }
    } else {
      __CrestBranch(437, 206, 0);
      __CrestLoad(456, (unsigned long )(& val), (long long )val);
#line 259
      flag = delValFromNode(val, myNode->link[pos]);
      __CrestHandleReturn(458, (long long )flag);
      __CrestStore(457, (unsigned long )(& flag));
    }
    }
    {
    __CrestLoad(461, (unsigned long )(& myNode->link[pos]), (long long )((unsigned long )myNode->link[pos]));
    __CrestLoad(460, (unsigned long )0, (long long )0);
    __CrestApply2(459, 13, (long long )(myNode->link[pos] != 0));
#line 261
    if (myNode->link[pos] != 0) {
      __CrestBranch(462, 208, 1);
      {
#line 262
      mem_5 = myNode->link[pos];
      {
      __CrestLoad(466, (unsigned long )(& mem_5->count), (long long )mem_5->count);
      __CrestLoad(465, (unsigned long )0, (long long )2);
      __CrestApply2(464, 16, (long long )(mem_5->count < 2));
#line 262
      if (mem_5->count < 2) {
        __CrestBranch(467, 211, 1);
        __CrestLoad(469, (unsigned long )(& pos), (long long )pos);
#line 263
        adjustNode(myNode, pos);
        __CrestClearStack(470);
      } else {
        __CrestBranch(468, 212, 0);

      }
      }
      }
    } else {
      __CrestBranch(463, 213, 0);

    }
    }
  } else {
    __CrestBranch(398, 214, 0);

  }
  }
  {
  __CrestLoad(471, (unsigned long )(& flag), (long long )flag);
  __CrestReturn(472);
#line 266
  return (flag);
  }
}
}
#line 270 "btree.c"
void deletion(int val , struct btreeNode *myNode ) 
{ 
  struct btreeNode *tmp ;
  int tmp___0 ;

  {
  __CrestCall(474, 14);
  __CrestStore(473, (unsigned long )(& val));
  __CrestLoad(475, (unsigned long )(& val), (long long )val);
#line 272
  tmp___0 = delValFromNode(val, myNode);
  __CrestHandleReturn(477, (long long )tmp___0);
  __CrestStore(476, (unsigned long )(& tmp___0));
  {
  __CrestLoad(480, (unsigned long )(& tmp___0), (long long )tmp___0);
  __CrestLoad(479, (unsigned long )0, (long long )0);
  __CrestApply2(478, 13, (long long )(tmp___0 != 0));
#line 272
  if (tmp___0 != 0) {
    __CrestBranch(481, 218, 1);
    {
    __CrestLoad(485, (unsigned long )(& myNode->count), (long long )myNode->count);
    __CrestLoad(484, (unsigned long )0, (long long )0);
    __CrestApply2(483, 12, (long long )(myNode->count == 0));
#line 276
    if (myNode->count == 0) {
      __CrestBranch(486, 219, 1);
#line 277
      tmp = myNode;
#line 278
      myNode = myNode->link[0];
#line 279
      free((void *)tmp);
      __CrestClearStack(488);
    } else {
      __CrestBranch(487, 220, 0);

    }
    }
  } else {
    __CrestBranch(482, 221, 0);
#line 273
    printf((char const   * __restrict  )"Given value is not present in B-Tree\n");
    __CrestClearStack(489);

#line 274
    goto return_label;
  }
  }
#line 282
  root = myNode;

  return_label: /* CIL Label */ 
  {
  __CrestReturn(490);
#line 270
  return;
  }
}
}
#line 287 "btree.c"
void searching(int val , int *pos , struct btreeNode *myNode ) 
{ 


  {
  __CrestCall(492, 15);
  __CrestStore(491, (unsigned long )(& val));
  {
  __CrestLoad(495, (unsigned long )(& myNode), (long long )((unsigned long )myNode));
  __CrestLoad(494, (unsigned long )0, (long long )0);
  __CrestApply2(493, 12, (long long )(myNode == 0));
#line 288
  if (myNode == 0) {
    __CrestBranch(496, 228, 1);

#line 289
    goto return_label;
  } else {
    __CrestBranch(497, 230, 0);

  }
  }
  {
  __CrestLoad(500, (unsigned long )(& val), (long long )val);
  __CrestLoad(499, (unsigned long )(& myNode->val[1]), (long long )myNode->val[1]);
  __CrestApply2(498, 16, (long long )(val < myNode->val[1]));
#line 292
  if (val < myNode->val[1]) {
    __CrestBranch(501, 232, 1);
    __CrestLoad(503, (unsigned long )0, (long long )0);
    __CrestStore(504, (unsigned long )pos);
#line 293
    *pos = 0;
  } else {
    __CrestBranch(502, 233, 0);
    __CrestLoad(505, (unsigned long )(& myNode->count), (long long )myNode->count);
    __CrestStore(506, (unsigned long )pos);
#line 295
    *pos = myNode->count;
    {
#line 295
    while (1) {
      while_continue: /* CIL Label */ ;
      {
      __CrestLoad(509, (unsigned long )(& val), (long long )val);
      __CrestLoad(508, (unsigned long )(& myNode->val[*pos]), (long long )myNode->val[*pos]);
      __CrestApply2(507, 16, (long long )(val < myNode->val[*pos]));
#line 295
      if (val < myNode->val[*pos]) {
        __CrestBranch(510, 238, 1);
        {
        __CrestLoad(514, (unsigned long )pos, (long long )*pos);
        __CrestLoad(513, (unsigned long )0, (long long )1);
        __CrestApply2(512, 14, (long long )(*pos > 1));
#line 295
        if (*pos > 1) {
          __CrestBranch(515, 239, 1);

        } else {
          __CrestBranch(516, 240, 0);
#line 295
          goto while_break;
        }
        }
      } else {
        __CrestBranch(511, 241, 0);
#line 295
        goto while_break;
      }
      }
      __CrestLoad(519, (unsigned long )pos, (long long )*pos);
      __CrestLoad(518, (unsigned long )0, (long long )1);
      __CrestApply2(517, 1, (long long )(*pos - 1));
      __CrestStore(520, (unsigned long )pos);
#line 295
      (*pos) --;
    }
    while_break: /* CIL Label */ ;
    }
    {
    __CrestLoad(523, (unsigned long )(& val), (long long )val);
    __CrestLoad(522, (unsigned long )(& myNode->val[*pos]), (long long )myNode->val[*pos]);
    __CrestApply2(521, 12, (long long )(val == myNode->val[*pos]));
#line 297
    if (val == myNode->val[*pos]) {
      __CrestBranch(524, 245, 1);
      __CrestLoad(526, (unsigned long )(& val), (long long )val);
#line 298
      printf((char const   * __restrict  )"Given data %d is present in B-Tree", val);
      __CrestClearStack(527);

#line 299
      goto return_label;
    } else {
      __CrestBranch(525, 248, 0);

    }
    }
  }
  }
  __CrestLoad(528, (unsigned long )(& val), (long long )val);
#line 302
  searching(val, pos, myNode->link[*pos]);
  __CrestClearStack(529);

  return_label: /* CIL Label */ 
  {
  __CrestReturn(530);
#line 287
  return;
  }
}
}
#line 307 "btree.c"
void traversal(struct btreeNode *myNode ) 
{ 
  int i ;

  {
  __CrestCall(531, 16);

  {
  __CrestLoad(534, (unsigned long )(& myNode), (long long )((unsigned long )myNode));
  __CrestLoad(533, (unsigned long )0, (long long )0);
  __CrestApply2(532, 13, (long long )(myNode != 0));
#line 309
  if (myNode != 0) {
    __CrestBranch(535, 253, 1);
    __CrestLoad(537, (unsigned long )0, (long long )0);
    __CrestStore(538, (unsigned long )(& i));
#line 310
    i = 0;
    {
#line 310
    while (1) {
      while_continue: /* CIL Label */ ;
      {
      __CrestLoad(541, (unsigned long )(& i), (long long )i);
      __CrestLoad(540, (unsigned long )(& myNode->count), (long long )myNode->count);
      __CrestApply2(539, 16, (long long )(i < myNode->count));
#line 310
      if (i < myNode->count) {
        __CrestBranch(542, 258, 1);

      } else {
        __CrestBranch(543, 259, 0);
#line 310
        goto while_break;
      }
      }
#line 311
      traversal(myNode->link[i]);
      __CrestClearStack(544);
      __CrestLoad(545, (unsigned long )(& myNode->val[i + 1]), (long long )myNode->val[i + 1]);
#line 312
      printf((char const   * __restrict  )"%d ", myNode->val[i + 1]);
      __CrestClearStack(546);
      __CrestLoad(549, (unsigned long )(& i), (long long )i);
      __CrestLoad(548, (unsigned long )0, (long long )1);
      __CrestApply2(547, 0, (long long )(i + 1));
      __CrestStore(550, (unsigned long )(& i));
#line 310
      i ++;
    }
    while_break: /* CIL Label */ ;
    }
#line 314
    traversal(myNode->link[i]);
    __CrestClearStack(551);
  } else {
    __CrestBranch(536, 263, 0);

  }
  }

  {
  __CrestReturn(552);
#line 307
  return;
  }
}
}
#line 318 "btree.c"
int main(void) 
{ 
  int val ;
  int ch ;
  int cnt ;
  int tmp ;
  int __retres5 ;

  {
  __globinit_btree();
  __CrestCall(553, 17);
  __CrestLoad(554, (unsigned long )0, (long long )5);
  __CrestStore(555, (unsigned long )(& cnt));
#line 320
  cnt = 5;
#line 321
  while (1) {
    while_continue: /* CIL Label */ ;
    __CrestLoad(556, (unsigned long )(& cnt), (long long )cnt);
    __CrestStore(557, (unsigned long )(& tmp));
#line 321
    tmp = cnt;
    __CrestLoad(560, (unsigned long )(& cnt), (long long )cnt);
    __CrestLoad(559, (unsigned long )0, (long long )1);
    __CrestApply2(558, 1, (long long )(cnt - 1));
    __CrestStore(561, (unsigned long )(& cnt));
#line 321
    cnt --;
    {
    __CrestLoad(564, (unsigned long )(& tmp), (long long )tmp);
    __CrestLoad(563, (unsigned long )0, (long long )0);
    __CrestApply2(562, 13, (long long )(tmp != 0));
#line 321
    if (tmp != 0) {
      __CrestBranch(565, 272, 1);

    } else {
      __CrestBranch(566, 273, 0);
#line 321
      goto while_break;
    }
    }
#line 322
    printf((char const   * __restrict  )"1. Insertion\t2. Deletion\n");
    __CrestClearStack(567);
#line 323
    printf((char const   * __restrict  )"3. Searching\t4. Traversal\n");
    __CrestClearStack(568);
#line 324
    printf((char const   * __restrict  )"5. Exit\nEnter your choice:");
    __CrestClearStack(569);
#line 326
    __CrestInt(& ch);
    __CrestLoad(570, (unsigned long )(& ch), (long long )ch);
#line 326
    fprintf((FILE * __restrict  )__stderrp, (char const   * __restrict  )"%d\n", ch);
    __CrestClearStack(571);
    {
    {
    __CrestLoad(574, (unsigned long )(& ch), (long long )ch);
    __CrestLoad(573, (unsigned long )0, (long long )1);
    __CrestApply2(572, 12, (long long )(ch == 1));
#line 328
    if (ch == 1) {
      __CrestBranch(575, 277, 1);
#line 328
      goto case_1;
    } else {
      __CrestBranch(576, 278, 0);

    }
    }
    {
    __CrestLoad(579, (unsigned long )(& ch), (long long )ch);
    __CrestLoad(578, (unsigned long )0, (long long )2);
    __CrestApply2(577, 12, (long long )(ch == 2));
#line 334
    if (ch == 2) {
      __CrestBranch(580, 280, 1);
#line 334
      goto case_2;
    } else {
      __CrestBranch(581, 281, 0);

    }
    }
    {
    __CrestLoad(584, (unsigned long )(& ch), (long long )ch);
    __CrestLoad(583, (unsigned long )0, (long long )3);
    __CrestApply2(582, 12, (long long )(ch == 3));
#line 340
    if (ch == 3) {
      __CrestBranch(585, 283, 1);
#line 340
      goto case_3;
    } else {
      __CrestBranch(586, 284, 0);

    }
    }
    {
    __CrestLoad(589, (unsigned long )(& ch), (long long )ch);
    __CrestLoad(588, (unsigned long )0, (long long )4);
    __CrestApply2(587, 12, (long long )(ch == 4));
#line 346
    if (ch == 4) {
      __CrestBranch(590, 286, 1);
#line 346
      goto case_4;
    } else {
      __CrestBranch(591, 287, 0);

    }
    }
    {
    __CrestLoad(594, (unsigned long )(& ch), (long long )ch);
    __CrestLoad(593, (unsigned long )0, (long long )5);
    __CrestApply2(592, 12, (long long )(ch == 5));
#line 349
    if (ch == 5) {
      __CrestBranch(595, 289, 1);
#line 349
      goto case_5;
    } else {
      __CrestBranch(596, 290, 0);

    }
    }
#line 351
    goto switch_default;
    case_1: /* CIL Label */ 
#line 329
    printf((char const   * __restrict  )"Enter your input:");
    __CrestClearStack(597);
#line 331
    __CrestInt(& val);
    __CrestLoad(598, (unsigned long )(& val), (long long )val);
#line 331
    fprintf((FILE * __restrict  )__stderrp, (char const   * __restrict  )"%d\n", val);
    __CrestClearStack(599);
    __CrestLoad(600, (unsigned long )(& val), (long long )val);
#line 332
    insertion(val);
    __CrestClearStack(601);
#line 333
    goto switch_break;
    case_2: /* CIL Label */ 
#line 335
    printf((char const   * __restrict  )"Enter the element to delete:");
    __CrestClearStack(602);
#line 337
    __CrestInt(& val);
    __CrestLoad(603, (unsigned long )(& val), (long long )val);
#line 337
    fprintf((FILE * __restrict  )__stderrp, (char const   * __restrict  )"%d\n", val);
    __CrestClearStack(604);
    __CrestLoad(605, (unsigned long )(& val), (long long )val);
#line 338
    deletion(val, root);
    __CrestClearStack(606);
#line 339
    goto switch_break;
    case_3: /* CIL Label */ 
#line 341
    printf((char const   * __restrict  )"Enter the element to search:");
    __CrestClearStack(607);
#line 343
    __CrestInt(& val);
    __CrestLoad(608, (unsigned long )(& val), (long long )val);
#line 343
    fprintf((FILE * __restrict  )__stderrp, (char const   * __restrict  )"%d\n", val);
    __CrestClearStack(609);
    __CrestLoad(610, (unsigned long )(& val), (long long )val);
#line 344
    searching(val, & ch, root);
    __CrestClearStack(611);
#line 345
    goto switch_break;
    case_4: /* CIL Label */ 
#line 347
    traversal(root);
    __CrestClearStack(612);
#line 348
    goto switch_break;
    case_5: /* CIL Label */ 
    __CrestLoad(613, (unsigned long )0, (long long )0);
#line 350
    exit(0);
    __CrestClearStack(614);
    switch_default: /* CIL Label */ 
#line 352
    printf((char const   * __restrict  )"U have entered wrong option!!\n");
    __CrestClearStack(615);
#line 353
    goto switch_break;
    switch_break: /* CIL Label */ ;
    }
#line 355
    printf((char const   * __restrict  )"\n");
    __CrestClearStack(616);
  }
  while_break: /* CIL Label */ 
  __CrestLoad(617, (unsigned long )0, (long long )0);
  __CrestStore(618, (unsigned long )(& __retres5));
#line 357
  __retres5 = 0;
  __CrestLoad(619, (unsigned long )(& __retres5), (long long )__retres5);
  __CrestReturn(620);
#line 318
  return (__retres5);
}
}
void __globinit_btree(void) 
{ 


  {
  __CrestInit();
}
}
